export const FETCH_PARKING_LOCATIONS_REQUEST = "FETCH_PARKING_LOCATIONS_REQUEST";
export const FETCH_PARKING_LOCATIONS_SUCCESS = "FETCH_PARKING_LOCATIONS_SUCCESS";
export const FETCH_PARKING_LOCATIONS_FAILURE = "FETCH_PARKING_LOCATIONS_FAILURE";
