/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface ParkSlot {
  id?: number;
  name?: string;
  address?: string;
  freeSlots?: number;
  busySlots?: number;
}

