/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ParkSlot
} from './generated.schemas';





  export const getParkSlotController = (axiosInstance: AxiosInstance = axios.default) => {
const getById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/park-slots/${id}`,{
        responseType: 'blob',
    ...options,}
    );
  }
const update = (
    id: number,
    parkSlot: ParkSlot, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.put(
      `/api/park-slots/${id}`,
      parkSlot,{
        responseType: 'blob',
    ...options,}
    );
  }
const _delete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/park-slots/${id}`,options
    );
  }
const getAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/park-slots`,{
        responseType: 'blob',
    ...options,}
    );
  }
const create = (
    parkSlot: ParkSlot, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/park-slots`,
      parkSlot,{
        responseType: 'blob',
    ...options,}
    );
  }
const testAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/park-slots/test`,{
        responseType: 'blob',
    ...options,}
    );
  }
return {getById,update,_delete,getAll,create,testAll}};
export type GetByIdResult = AxiosResponse<Blob>
export type UpdateResult = AxiosResponse<Blob>
export type _DeleteResult = AxiosResponse<void>
export type GetAllResult = AxiosResponse<Blob>
export type CreateResult = AxiosResponse<Blob>
export type TestAllResult = AxiosResponse<Blob>
